server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: main-service
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_empty
    banner: false
  mapper-locations: classpath*:/mappers/*.xml

logging:
  level:
    root: info
