server:
  port: 7777

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<INTERNAL_IP>:13306/wechat-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mysql
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  data:
    redis:
      host: <INTERNAL_IP>
      port: 16379
      password: redis
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: <INTERNAL_IP>:8848
        username: nacos
        password: nacos
  rabbitmq:
    host: <INTERNAL_IP>
    port: 5682
    username: solisamicus
    password: rabbitmq
    virtual-host: wechat-dev

zookeeper:
  curator:
    host: <INTERNAL_IP>
    port: 2181
    connectionTimeout: 30000
    sessionTimeout: 3000
    sleepBetweenRetry: 2000
    maxRetries: 3
    namespace: wechat-dev