server:
  port: 5555

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
minio:
  endpoint: http://127.0.0.1:9000
  fileHost: http://127.0.0.1:9000
  bucketName: wechat
  accessKey: solisamicus
  secretKey: miniowechat
