server:
  port: 5555

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  rabbitmq:
    host: 127.0.0.1
    port: 5682
    username: solisamicus
    password: rabbitmq
    virtual-host: wechat-dev
minio:
  endpoint: http://192.168.10.24:9000
  fileHost: http://192.168.10.24:9000
  bucketName: wechat
  accessKey: solisamicus
  secretKey: miniowechat
